VPATH += ../include/libnet
VPATH += ../src

CFLAGS += -Wall -Wextra -Werror -Wfatal-errors -std=c99
CFLAGS += -I ../include

.PHONY: all
all: example1

example1.o: example1.c stack.h

example1: example1.o -lnet

.PHONY: clean
clean:

.PHONY: test
test:

.PHONY: install
install:

